name: Deploy Dist
# on: [push, workflow_dispatch]
on:
  push:
    branches:
      - main
      - "feature/**"
    paths-ignore:
      - ".github/workflows/*"
      - "README.md"
  workflow_dispatch:
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      # Below is the code that clones the repository in a harder way
      # - name: Clone the code on the machine
      # run: |
      #   echo "Cloning the code on the machine"
      #   echo "${{toJson(github)}}"
      #   git clone https://github.com/${{github.repository}}.git

      # Now below is the code that clones the repository in a simpler way
      - name: Checkout
        uses: actions/checkout@v4.2.2
      # # Below is the code that sets up Node.js environment
      - name: Setup Node.js environment
        uses: actions/setup-node@v4.4.0
        with:
          node-version: "20"
      - name: cache Dependencies
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
      - name: Install dependencies
        # This step installs the dependencies using npm ci (clean install)
        run: npm ci
      - name: Run tests using vite
        # This step runs the tests using npm run test
        run: npm run test
  build:
    needs: test
    runs-on: ubuntu-latest
     # Get the code from the repository
    steps:
      - name: Get Code
        uses: actions/checkout@v4.2.2
      # Setup Node.js environment
      - name: Setup Node.js environment
        uses: actions/setup-node@v4.4.0
        with:
          node-version: "20"
      - name: cache Dependencies
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
      - name: Install dependencies
        # This step installs the dependencies using npm ci (clean install)
        run: npm ci
      - name: Build Project
        # This step runs the build using npm run build
        run: npm run build
      - name: Upload dist folder---->
        uses: actions/upload-artifact@v4.6.2
        with:
          name: dist-files
          path: dist

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download dist folder<------
        uses: actions/download-artifact@v4.3.0
        with:
          name: dist-files
      - name: Deploy
        # This step runs the build using npm run build
        run: echo "Deploying the dist folder"
